name: flutter_application_3
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  path: ^1.8.0
  sqflite: ^2.0.0+4
  path_provider: ^2.1.1
  get: ^4.6.6
  webview_flutter: ^4.4.1
  flutter_html: ^3.0.0-beta.2
  video_player: ^2.7.2
  persistent_bottom_nav_bar: ^5.0.2
  flutter_inappwebview: ^5.8.0
  go_router: ^10.1.2
  sliding_clipped_nav_bar: ^3.1.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/food_recipe.db
  fonts:
    - family: Dangrek
      fonts:
        - asset: assets/fonts/Dangrek-Regular.ttf
